server:
  port: ${PORT:9080} #8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    # No restrictions on table names
    url: jdbc:h2:mem:h2
    # No restrictions on username and password
    username: root
    password: 123


logging:
  config: classpath:logback.xml
  level:
    root: INFO
